### PR TITLE
Fiz dialyzer warnings and enable the untyped records warning

### PR DESCRIPTION
**Pull request by Vagabond**
This does not address the warnings generated by the ?assert macros used in cuttlefish_unit. I don't really know how to deal with those.

cc @joedevivo @seancribbs

### CODE REVIEW

**Comment by Vagabond** [comment]
I fixed the error type spec as well as the unmatched return values. Some of the unmatched return values I ignore, some I matched, but I may have made the wrong call on some of them, hard to tell.

**Comment by seancribbs** [comment]
Updating neotoma to 1.7.2 and rebuilding the pegs removed those warnings. The `cuttlefish_unit` warnings can be addressed by some restructuring, I'll look again in the morning.

**Comment by seancribbs** [comment]
Eh, I can't leave a dialyzer warning unturned. Pooshed.

**Comment by joedevivo** [comment]
pulled new neotoma dep, still see this:

```
conf_parse.erl:99: Expression produces a value of type tid(), but this value is unmatched
cuttlefish_duration_parse.erl:46: Expression produces a value of type tid(), but this value is unmatched
```

**Comment by seancribbs** [comment]
@joedevivo Run a clean or remove the .erl files for those, then recompile/dialyze.

**Comment by joedevivo** [comment]
@seancribbs you're the man!

:+1:

**Comment by joedevivo** [comment]
BTW, I'm loving the "Fiz" typo

**Comment by joedevivo** [comment]
@Vagabond merge at will

**Pull request merged**
