### PR TITLE
Update rebar from binary under riak

### PR DESCRIPTION
**Pull request by shino**
After cloning riak develop branch, `make` fails with the following error message:

```
ERROR: Failed to get ebin/ directory for goldrush escript_incl_apps.ERROR: escriptize failed while processing /home/shino/work/basho/git/riak-2.0/deps/cuttlefish: rebar_abort
ERROR: Command [compile] failed!
make: *** [compile] Error 1
```

$ ./rebar --version
rebar 2.1.0-pre R14B04 20131017_164918 git 2.1.0-pre-168-gaa46d85

(I don't yet dig into details of the error, but I think faster is better)

### CODE REVIEW

**Comment by seancribbs** [comment]
@shino This is after you did a get-deps or update-deps?

**Comment by shino** [comment]
@seancribbs  Yes. After `./rebar get-deps`, error occurs in `make compile`.
Doesn't the error occur in your environment? Kota and Kaz also came across the same error, so it may depends on locale setting(s).

**Comment by shino** [comment]
One environmental thing found.

When `ERL_LIBS` is not set, `make compile` succeeds:

```
$ unset ERL_LIBS
$ make compile
./rebar compile
==> node_package (compile)
==> goldrush (compile)
==> lager (compile)
==> syslog (compile)
==> lager_syslog (compile)
==> cluster_info (compile)
==> sidejob (compile)
==> erlang_js (compile)
make[1]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js'
cd c_src; make
make[2]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js/c_src'
make[2]: Nothing to be done for `js'.
make[2]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js/c_src'
make[1]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js'
==> meck (compile)
==> getopt (compile)
==> neotoma (compile)
==> kvc (compile)
==> cuttlefish (compile)
==> cuttlefish (escriptize)
==> bitcask (compile)
==> ebloom (compile)
==> eper (compile)
==> edown (compile)
==> sext (compile)
==> poolboy (compile)
==> basho_stats (compile)
==> riak_sysmon (compile)
==> bear (compile)
==> folsom (compile)
==> ranch (compile)
==> pbkdf2 (compile)
==> eleveldb (compile)
make[1]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make  all-am
make[2]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[2]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[2]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
test -z "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib" || /bin/mkdir -p "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib"
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libsnappy.la '/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib'
libtool: install: /usr/bin/install -c .libs/libsnappy.so.1.1.2 /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib/libsnappy.so.1.1.2
libtool: install: (cd /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib && { ln -s -f libsnappy.so.1.1.2 libsnappy.so.1 || { rm -f libsnappy.so.1 && ln -s libsnappy.so.1.1.2 libsnappy.so.1; }; })
libtool: install: (cd /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib && { ln -s -f libsnappy.so.1.1.2 libsnappy.so || { rm -f libsnappy.so && ln -s libsnappy.so.1.1.2 libsnappy.so; }; })
libtool: install: /usr/bin/install -c .libs/libsnappy.lai /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib/libsnappy.la
libtool: install: /usr/bin/install -c .libs/libsnappy.a /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib/libsnappy.a
libtool: install: chmod 644 /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib/libsnappy.a
libtool: install: ranlib /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib/libsnappy.a
libtool: finish: PATH="/opt/erlang/R15B03_1_sfwi/lib/erlang/erts-5.9.3.1/bin:/opt/erlang/R15B03_1_sfwi/lib/erlang/bin:/home/shino/.nvm/v0.11.1/bin:/home/shino/.rbenv/shims:/opt/shino/virtualenvs/py27_base/bin:/home/shino/bin:/home/shino/local/bin:/opt/erlang/R15B03_1_sfwi/bin:/usr/local/texlive/2012/bin/x86_64-linux:/home/shino/.rbenv/bin:/home/shino/local/fop:/opt/shino/src/mysql/mysql-cluster-gpl-7.2.8-linux2.6-x86_64/bin:/usr/local/pgsql-824/bin:/usr/local/maven/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/home/shino/local/android-sdk-mac_x86/tools:/home/shino/src/depot_tools/depot_tools:/usr/bin:/bin:/usr/sbin:/sbin:/sbin" ldconfig -n /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
test -z "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/share/doc/snappy" || /bin/mkdir -p "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/share/doc/snappy"
 /usr/bin/install -c -m 644 ChangeLog COPYING INSTALL NEWS README format_description.txt '/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/share/doc/snappy'
test -z "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/include" || /bin/mkdir -p "/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/include"
 /usr/bin/install -c -m 644 snappy.h snappy-sinksource.h snappy-stubs-public.h snappy-c.h '/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/system/include'
make[2]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/snappy-1.0.4'
make[1]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/leveldb'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/eleveldb/c_src/leveldb'
==> riak_core (compile)
==> riak_pipe (compile)
==> protobuffs (compile)
==> riak_pb (compile)
==> mochiweb (compile)
==> ibrowse (compile)
==> webmachine (compile)
==> riak_api (compile)
==> riak_dt (compile)
==> riak_kv (compile)
==> merge_index (compile)
==> lucene_parser (compile)
==> riak_search (compile)
==> erlydtl (compile)
==> riak_control (compile)
Compiled handlebars asset priv/admin/js/generated/templates.js
==> riaknostic (compile)
==> yokozuna (compile)
Solr already exists, exiting
Build the yokozuna.jar...
Compile...
Create yokozuna.jar...
added manifest
adding: com/basho/yokozuna/handler/(in = 0) (out= 0)(stored 0%)
adding: com/basho/yokozuna/handler/EntropyData.java(in = 6660) (out= 2157)(deflated 67%)
adding: com/basho/yokozuna/handler/EntropyData.class(in = 5817) (out= 2878)(deflated 50%)
adding: com/basho/yokozuna/query/(in = 0) (out= 0)(stored 0%)
adding: com/basho/yokozuna/query/SimpleQueryExample.class(in = 1495) (out= 749)(deflated 49%)
adding: com/basho/yokozuna/query/SimpleQueryExample.java(in = 1517) (out= 566)(deflated 62%)
Finished building yokozuna.jar...
Create yz_monitor.jar...
added manifest
adding: com/basho/yokozuna/monitor/(in = 0) (out= 0)(stored 0%)
adding: com/basho/yokozuna/monitor/Monitor.class(in = 1295) (out= 788)(deflated 39%)
adding: com/basho/yokozuna/monitor/Monitor.java(in = 2119) (out= 939)(deflated 55%)
Finished building yz_monitor.jar...
==> canola (compile)
==> riak_auth_mods (compile)
==> rebar_lock_deps_plugin (compile)
==> rel (compile)
==> riak (compile)
==> riak-2.0 (compile)
```

Otherwise, `make compile` fails:

```
$ ERL_LIBS=spam make compile
./rebar compile
==> node_package (compile)
==> goldrush (compile)
==> lager (compile)
==> syslog (compile)
==> lager_syslog (compile)
==> cluster_info (compile)
==> sidejob (compile)
==> erlang_js (compile)
make[1]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js'
cd c_src; make
make[2]: Entering directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js/c_src'
make[2]: Nothing to be done for `js'.
make[2]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js/c_src'
make[1]: Leaving directory `/home/shino/work/basho/git/riak-2.0/deps/erlang_js'
==> meck (compile)
==> getopt (compile)
==> neotoma (compile)
==> kvc (compile)
==> cuttlefish (compile)
==> cuttlefish (escriptize)
ERROR: Failed to get ebin/ directory for goldrush escript_incl_apps.ERROR: escriptize failed while processing /home/shino/work/basho/git/riak-2.0/deps/cuttlefish: rebar_abort
ERROR: Command [compile] failed!
make: *** [compile] Error 1
```

**Comment by shino** [comment]
Result of `git bisect` in rebar repo (not in riak repo): https://gist.github.com/shino/d299951f56f06b6cdc4f

`make compile` suceeds both with and without `ERL_LIBS` at the commit https://github.com/rebar/rebar/commit/620c4b0?w=1

**Comment by Licenser** [comment]
I can confirm this problem and the resolution (ran into the same thing)

**Comment by joedevivo** [comment]
we can haz new rebar!

**Comment by Licenser** [comment]
<3

**Pull request merged**
