### PR TITLE
Add +scl and +sub support

### PR DESCRIPTION
**Pull request by slfritchie**
Partially addresses #108.  Both flags (but especially "+scl false") is necessary (in part) for avoiding scheduler collapse, even with R16 (sadpanda).

### CODE REVIEW

**Comment by seancribbs** [comment]
Is there a default value for these emulator flags, or should they just remain commented?

**Comment by seancribbs** [comment]
<del>Also, if this is still an issue on R16, should it not be 2.0 or 2.0.1 milestone?</del> Woops, just saw the other PR.

**Comment by slfritchie** [comment]
I think that they should remain commented, rather than push them to a default that might change with the VM.  Thoughts?

**Comment by seancribbs** [comment]
@slfritchie Seems reasonable. Can you cherry-pick the last commit from your other PR here?

**Comment by slfritchie** [comment]
Pushed.

**Comment by seancribbs** [comment]
:+1: 8e2f913

**Comment by seancribbs** [comment]
Treating this identical PR as reviewed by CSEs already.

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
