### PR TITLE
Add support for -kernel net_ticktime

### PR DESCRIPTION
**Pull request by slfritchie**
Partially addresses https://github.com/basho/riak_core/pull/489

### CODE REVIEW

**Comment by seancribbs** [comment]
Is this not the same as the application environment:

``` erlang
{kernel, [{net_ticktime, N}]}
```

Is there a reason it needs to be a vm.args flag?

**Comment by slfritchie** [comment]
Nodetool doesn't have goop to scrape stuff out of an Erlang-style .app file.

**Comment by kellymclaughlin** [comment]
Verified that this PR along with [this](https://github.com/basho/node_package/pull/113) node_package PR resolves the issues I reported [here](https://github.com/basho/riak_core/pull/489).

**Comment by seancribbs** [comment]
+1

**Comment by seancribbs** [comment]
@borshop where you at?

**Comment by slfritchie** [comment]
Oh, this is a Bors repo, derp, my bad.

**Comment by slfritchie** [comment]
@borshop +1 8a61379b5d9bd456281d9ea574ffc80e5bf0069a

**Pull request merged**
