### PR TITLE
Increase default for ERL_MAX_PORTS (+Q) setting to 262144 (JIRA-2332)

### PR DESCRIPTION
**Pull request by JeetKunDoug**
Resolves basho/riak#801

### CODE REVIEW

**Comment by JeetKunDoug** [comment]
@mrallen1 can you take a look at this and +1 when you have a moment please?

**Comment by jadeallenx** [comment]
:+1:  657947b

**Comment by jadeallenx** [comment]
All tests and dialyzer are green.

**Comment by JeetKunDoug** [comment]
@borshop merge

**Pull request merged**
