### PR TITLE
Backport #169 and #171 from develop

### PR DESCRIPTION
**Pull request by seancribbs**
This is a rebase of #169 and #171 from develop, plus some other things that seem not up-to-date.

### CODE REVIEW

**Comment by joedevivo** [comment]
https://www.youtube.com/watch?feature=player_detailpage&v=DbxcHVmdJos#t=102

**Comment by hazen** [comment]
So far, so good:

```
  All 288 tests passed.
```

**Comment by hazen** [comment]
:+1: 2879904

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
