### PR TITLE
rebar clean will now remove the generated .erl files from neotoma

### PR DESCRIPTION
**Pull request by macintux**

### CODE REVIEW

**Comment by tburghart** [comment]
What, if any, mechanism is in place to ensure that these are generated files?

My concern is that if, at some point in the future, the files were hand-crafted and checked in by someone who didn't know that they were explicitly flagged for deletion in rebar.config, rebar would merrily delete them. The breakage could be corrected, of course, but how much head scratching might be required to find the problem is indeterminate.

**Comment by macintux** [comment]
There are no mechanisms at the moment. I was hoping that this was something that rebar could interpret natively, but I don't believe that to be the case. Although, I have not taken a close look at the neotoma plugin for rebar.

**Comment by macintux** [comment]
basho/rebar#407 addresses this within rebar itself, but no idea if/when that'll become a reality.

**Comment by macintux** [comment]
One alternative to this approach: include a custom rebar in cuttlefish with the neotoma compiler patch. Seems a bit hacky but so is including rebar at all.

**Pull request closed without merging**
