### PR TITLE
Test `riak config` commands with legacy app.config / vm.args

### PR DESCRIPTION
**Pull request by joedevivo**
https://twitter.com/densoneold/status/691891562

make sure that the command line output for these commands exits cleanly

### CODE REVIEW

**Comment by joedevivo** [comment]
`./bin/riak config effective` will actually show output that is misleading when run in legacy config environments.

**Comment by seancribbs** [comment]
Ayo, you've got a dialyzer warning:

```
cuttlefish_escript.erl:107: Expression produces a value of type 'ok' | ['ok'], but this value is unmatched
```

**Comment by seancribbs** [comment]
:+1: 4cedced

**Comment by seancribbs** [comment]
@borshop: retry 4cedced

**Comment by joedevivo** [comment]
@borshop I'm sorry for whatever I did

**Comment by seancribbs** [comment]
+1 4cedced1

**Comment by reiddraper** [comment]
I'm not sure why bors isn't commenting. I'm looking into it though.

**Comment by Vagabond** [comment]
+1 4cedced1

**Comment by joedevivo** [comment]
@borshop merge

**Pull request merged**
