### PR TITLE
+a is missing from erlang_vm.schema

### PR DESCRIPTION
**Pull request by seancribbs**
see http://erlang.org/doc/man/erl.html for more details on `+a`.

### CODE REVIEW

**Comment by seancribbs** [comment]
@jrwest Added to the schema, would love a review from you.

**Comment by jrwest** [comment]
I'll take it this week. 

Jordan

**Comment by seancribbs** [comment]
- [x] Eng +1 (@jrwest)
- [x] CSE +1

**Comment by jrwest** [comment]
haven't forgotten this. reviewing today.

**Comment by jrwest** [comment]
+1  89f566d

changes look good. tests pass. things generate as expected. nice work w/ the extra formatting on the system wordsize!

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
