### PR TITLE
Give more helpful output during generate failure

### PR DESCRIPTION
**Pull request by rzezeski**
I am trying to make a stagedevrel on riak-pre9 and keep getting this error.

```
ERROR: generate failed while processing /root/yz-src-verify/riak_yz/rel: {'EXIT',
    {badarg,
        [{io_lib,format,
            ["Default: ~s",
              [{error,"could not convert off of type flag to a string"}]],
            [{file,"io_lib.erl"},{line,155}]},
        {cuttlefish_conf,generate_comments,1,
            [{file,"src/cuttlefish_conf.erl"},{line,125}]},
...
```

It is kind of helpful but gives me no idea which file/mapping generated it. This patch adds more info.

```
ERROR: generate failed while processing /root/yz-src-verify/riak_yz/rel: {{mapping,["dtrace"],
          "riak_core.dtrace_support",off,undefined,
          [flag],
          basic,
          ["DTrace support Do not enable 'dtrace' unless your Erlang/OTP",
          "runtime is compiled to support DTrace.  DTrace is available in",
          "R15B01 (supported by the Erlang/OTP official source package) and in",
          "R14B04 via a custom source repository & branch."],
          undefined,[],false,[]},
badarg,
[{io_lib,format,
          ["Default: ~s",
          [{error,"could not convert off of type flag to a string"}]],
          [{file,"io_lib.erl"},{line,155}]},
...
```

### CODE REVIEW

**Comment by seancribbs** [comment]
Also, updating cuttlefish will help, that was a bug we fixed late last week.

**Comment by rzezeski** [comment]
I think @jaredmorrow ran into it today? But this would help in future if stuff failed to generate. I had no idea where to look without it.

**Comment by seancribbs** [comment]
Ah, @joedevivo found the source of the problem, it was deeper than I thought. #103

**Comment by seancribbs** [comment]
I'd love to see a unit test for this.

**Comment by seancribbs** [comment]
Reopen if you feel strongly about this @rzezeski

**Pull request closed without merging**
