### PR TITLE
Update lager to 2.2.3

### PR DESCRIPTION
**Pull request by nickelization**

### CODE REVIEW

**Comment by fadushin** [comment]
+1 c6f9aef

**Comment by nickelization** [comment]
:+1: c6f9aef

**Comment by macintux** [comment]
I suspect you both got it wrong. Needs the : : around it, but don't allow auto-complete on the emoji or Bors won't recognize it.

**Comment by nickelization** [comment]
@macintux Thanks, yeah I actually knew about that wrinkle, and didn't allow it to auto-complete the emoji, so hopefully it should work this time. (I did think that just a bare "+1" without the : characters should've worked though...but I guess I'm not positive about that.)

**Comment by macintux** [comment]
Actually per our Bors page the +1 should have worked. Dunno.

219 doesn’t show up in the queue status, so maybe Bors is just out to lunch entirely.

-John

**Comment by nickelization** [comment]
I've asked around for help, but nobody seems to know how to fix Bors, so I'm going to give up and merge this manually.

**Pull request merged**
